function colourCode = areaColours2(areaIdentifier)
% colourCode = areaColours2(areaIdentifier)
%
% Function outputs a colour code appropriate for a given area identifier.
% Input: areaIdentifier - areaCode, areaID, or areaName. areaCode is a
%                         number that uniquely identifies the area. areaID
%                         is area ID in the form of seriesName(15:end).
%                         areaName is an area acronym (e.g., S1).
% Output: colourCode.

[~,~,areaName] = determineArea(areaIdentifier);

if strcmp(areaName,'Th') || strcmp(areaName,'lTh') || strcmp(areaName,'rTh') ||...
    strcmp(areaName,'Th+') || strcmp(areaName,'lTh+') || strcmp(areaName,'rTh+') ||...
    strcmp(areaName,'ThPos') || strcmp(areaName,'lThPos') || strcmp(areaName,'rThPos') ||...
    strcmp(areaName,'Th-') || strcmp(areaName,'lTh-') || strcmp(areaName,'rTh-') ||...
    strcmp(areaName,'ThNeg') || strcmp(areaName,'lThNeg') || strcmp(areaName,'rThNeg')
  colourCode = matlabColours(6);
elseif strcmp(areaName,'VB') || strcmp(areaName,'lVB') || strcmp(areaName,'rVB') ||...
    strcmp(areaName,'VB+') || strcmp(areaName,'lVB+') || strcmp(areaName,'rVB+') ||...
    strcmp(areaName,'VBPos') || strcmp(areaName,'lVBPos') || strcmp(areaName,'rVBPos') ||...
    strcmp(areaName,'VB-') || strcmp(areaName,'lVB-') || strcmp(areaName,'rVB-') ||...
    strcmp(areaName,'VBNeg') || strcmp(areaName,'lVBNeg') || strcmp(areaName,'rVBNeg')
  colourCode = matlabColours(1);
elseif strcmp(areaName,'Po') || strcmp(areaName,'lPo') || strcmp(areaName,'rPo') ||...
    strcmp(areaName,'Po+') || strcmp(areaName,'lPo+') || strcmp(areaName,'rPo+') ||...
    strcmp(areaName,'PoPos') || strcmp(areaName,'lPoPos') || strcmp(areaName,'rPoPos') ||...
    strcmp(areaName,'Po-') || strcmp(areaName,'lPo-') || strcmp(areaName,'rPo-') ||...
    strcmp(areaName,'PoNeg') || strcmp(areaName,'lPoNeg') || strcmp(areaName,'rPoNeg')
  colourCode = matlabColours(8);
elseif strcmp(areaName,'LGN') || strcmp(areaName,'lLGN') || strcmp(areaName,'rLGN') ||...
    strcmp(areaName,'LGN+') || strcmp(areaName,'lLGN+') || strcmp(areaName,'rLGN+') ||...
    strcmp(areaName,'LGNPos') || strcmp(areaName,'lLGNPos') || strcmp(areaName,'rLGNPos') ||...
    strcmp(areaName,'LGN-') || strcmp(areaName,'lLGN-') || strcmp(areaName,'rLGN-') ||...
    strcmp(areaName,'LGNNeg') || strcmp(areaName,'lLGNNeg') || strcmp(areaName,'rLGNNeg')
  colourCode = matlabColours(2);
elseif strcmp(areaName,'LP') || strcmp(areaName,'lLP') || strcmp(areaName,'rLP') ||...
    strcmp(areaName,'LP+') || strcmp(areaName,'lLP+') || strcmp(areaName,'rLP+') ||...
    strcmp(areaName,'LPPos') || strcmp(areaName,'lLPPos') || strcmp(areaName,'rLPPos') ||...
    strcmp(areaName,'LP-') || strcmp(areaName,'lLP-') || strcmp(areaName,'rLP-') ||...
    strcmp(areaName,'LPNeg') || strcmp(areaName,'lLPNeg') || strcmp(areaName,'rLPNeg')
  colourCode = matlabColours(10);
elseif strcmp(areaName,'S1') || strcmp(areaName,'lS1') || strcmp(areaName,'rS1') ||...
    strcmp(areaName,'S1+') || strcmp(areaName,'lS1+') || strcmp(areaName,'rS1+') ||...
    strcmp(areaName,'S1Pos') || strcmp(areaName,'lS1Pos') || strcmp(areaName,'rS1Pos') ||...
    strcmp(areaName,'S1-') || strcmp(areaName,'lS1-') || strcmp(areaName,'rS1-') ||...
    strcmp(areaName,'S1Neg') || strcmp(areaName,'lS1Neg') || strcmp(areaName,'rS1Neg')
  colourCode = matlabColours(13);
elseif strcmp(areaName,'V1') || strcmp(areaName,'lV1') || strcmp(areaName,'rV1') ||...
    strcmp(areaName,'V1+') || strcmp(areaName,'lV1+') || strcmp(areaName,'rV1+') ||...
    strcmp(areaName,'V1Pos') || strcmp(areaName,'lV1Pos') || strcmp(areaName,'rV1Pos') ||...
    strcmp(areaName,'V1-') || strcmp(areaName,'lV1-') || strcmp(areaName,'rV1-') ||...
    strcmp(areaName,'V1Neg') || strcmp(areaName,'lV1Neg') || strcmp(areaName,'rV1Neg')
  colourCode = matlabColours(11);
elseif strcmp(areaName,'V2') || strcmp(areaName,'lV2') || strcmp(areaName,'rV2') ||...
    strcmp(areaName,'V2+') || strcmp(areaName,'lV2+') || strcmp(areaName,'rV2+') ||...
    strcmp(areaName,'V2Pos') || strcmp(areaName,'lV2Pos') || strcmp(areaName,'rV2Pos') ||...
    strcmp(areaName,'V2-') || strcmp(areaName,'lV2-') || strcmp(areaName,'rV2-') ||...
    strcmp(areaName,'V2Neg') || strcmp(areaName,'lV2Neg') || strcmp(areaName,'rV2Neg')
  colourCode = datamean([matlabColours(11); matlabColours(5)]);
elseif strcmp(areaName,'VIS') || strcmp(areaName,'lVIS') || strcmp(areaName,'rVIS') ||...
    strcmp(areaName,'VIS+') || strcmp(areaName,'lVIS+') || strcmp(areaName,'rVIS+') ||...
    strcmp(areaName,'VISPos') || strcmp(areaName,'lVISPos') || strcmp(areaName,'rVISPos') ||...
    strcmp(areaName,'VIS-') || strcmp(areaName,'lVIS-') || strcmp(areaName,'rVIS-') ||...
    strcmp(areaName,'VISNeg') || strcmp(areaName,'lVISNeg') || strcmp(areaName,'rVISNeg')
  colourCode = matlabColours(5);
elseif strcmp(areaName,'RSC') || strcmp(areaName,'lRSC') || strcmp(areaName,'rRSC') ||...
    strcmp(areaName,'RSC+') || strcmp(areaName,'lRSC+') || strcmp(areaName,'rRSC+') ||...
    strcmp(areaName,'RSCPos') || strcmp(areaName,'lRSCPos') || strcmp(areaName,'rRSCPos') ||...
    strcmp(areaName,'RSC-') || strcmp(areaName,'lRSC-') || strcmp(areaName,'rRSC-') ||...
    strcmp(areaName,'RSCNeg') || strcmp(areaName,'lRSCNeg') || strcmp(areaName,'rRSCNeg')
  colourCode = matlabColours(3);
elseif strcmp(areaName,'Cx') || strcmp(areaName,'lCx') || strcmp(areaName,'rCx') ||...
    strcmp(areaName,'Cx+') || strcmp(areaName,'lCx+') || strcmp(areaName,'rCx+') ||...
    strcmp(areaName,'CxPos') || strcmp(areaName,'lCxPos') || strcmp(areaName,'rCxPos') ||...
    strcmp(areaName,'Cx-') || strcmp(areaName,'lCx-') || strcmp(areaName,'rCx-') ||...
    strcmp(areaName,'CxNeg') || strcmp(areaName,'lCxNeg') || strcmp(areaName,'rCxNeg')
  colourCode = datamean([matlabColours(13); matlabColours(3)]);
elseif strcmp(areaName,'CA') || strcmp(areaName,'lCA') || strcmp(areaName,'rCA') ||...
    strcmp(areaName,'CA+') || strcmp(areaName,'lCA+') || strcmp(areaName,'rCA+') ||...
    strcmp(areaName,'CAPos') || strcmp(areaName,'lCAPos') || strcmp(areaName,'rCAPos') ||...
    strcmp(areaName,'CA-') || strcmp(areaName,'lCA-') || strcmp(areaName,'rCA-') ||...
    strcmp(areaName,'CANeg') || strcmp(areaName,'lCANeg') || strcmp(areaName,'rCANeg')
  colourCode = matlabColours(4);
elseif strcmp(areaName,'DG') || strcmp(areaName,'lDG') || strcmp(areaName,'rDG') ||...
    strcmp(areaName,'DG+') || strcmp(areaName,'lDG+') || strcmp(areaName,'rDG+') ||...
    strcmp(areaName,'DGPos') || strcmp(areaName,'lDGPos') || strcmp(areaName,'rDGPos') ||...
    strcmp(areaName,'DG-') || strcmp(areaName,'lDG-') || strcmp(areaName,'rDG-') ||...
    strcmp(areaName,'DGNeg') || strcmp(areaName,'lDGNeg') || strcmp(areaName,'rDGNeg')
  colourCode = matlabColours(12);
elseif strcmp(areaName,'Hp') || strcmp(areaName,'lHp') || strcmp(areaName,'rHp') ||...
    strcmp(areaName,'Hp+') || strcmp(areaName,'lHp+') || strcmp(areaName,'rHp+') ||...
    strcmp(areaName,'HpPos') || strcmp(areaName,'lHpPos') || strcmp(areaName,'rHpPos') ||...
    strcmp(areaName,'Hp-') || strcmp(areaName,'lHp-') || strcmp(areaName,'rHp-') ||...
    strcmp(areaName,'HpNeg') || strcmp(areaName,'lHpNeg') || strcmp(areaName,'rHpNeg')
  colourCode = datamean([matlabColours(4); matlabColours(12)]);
end