function str = summaryStatsPhase(uolPhase_ca, cond, comp, frequency)

[fPEst, fWTest, pEst, U2, pObs, U2Obs] = dispPhaseHistoStats_ca(uolPhase_ca, cond, comp, frequency);
str = sprintf(['Comparing %s means for %g and %g Hz using Mardia-Watson-Wheeler Uniform-Scores Test gives p-values '...
    'of %1.3g (W=%1.3g) and %1.3g (W=%1.3g), respectively. Estimated Watson test gives p-values of %1.3g (U2=%1.3g) and %1.3g (U2=%1.3g) '...
    'while observed Watson test gives p-values of %1.3g (U=%1.3g) and %1.3g (U=%1.3g), respectively.'],...
    comp, frequency(1), frequency(2), fPEst(1), fWTest(1), fPEst(2), fWTest(2), pEst(1), U2(1), pEst(2), U2(2), pObs(1), U2Obs(1), pObs(2), U2Obs(2));