repository = 'allensdk'; % 'uol' or 'allensdk'
subpop = 'positive'; %'all', 'positive', 'negative'
fullRun = true; % Full data analyses (true) or only creating figures (false)
includeRuns = 'noRun'; % 'run', 'noRun'

params

if ~exist('allData', 'var') && fullRun % load allData which contains full spiking data
  if strcmp(repository,'uol')
    load([dataDir_local filesep '001_uol' filesep includeRuns filesep 'allData_uol.mat']);
  elseif strcmp(repository,'allensdk') %#ok<*UNRCH>
    load([dataDir_local filesep '002_allen' filesep includeRuns filesep 'allData_allensdk.mat']);
  end
end

pupilCorrFractionPlot
% pupilCorrFractionPlot2

% reverse = false;
% globalPhaseAnalysisLFP
% reverse = true;
% globalPhaseAnalysisLFP
% 
% globalEyeAnalysisLFP

% qualityCheck = false;
% globalBetaAnalysis
% if strcmp(repository,'uol')
%   qualityCheck = true;
%   globalBetaAnalysis
% end

qualityCheck = false; %#ok<*NASGU>
globalPhaseAnalysis_unitsLocal
% if strcmp(repository,'all') || strcmp(repository,'uol')
%   qualityCheck = true;
%   globalPhaseAnalysis_unitsLocal
% end

% if strcmp(repository,'uol')
%   qualityCheck = false;
%   globalConditionsAnalysis
%   %qualityCheck = true;
%   %globalConditionsAnalysis
% end

% qualityCheck = false;
% globalPhaseAnalysis_unitsLaminar % run twice
% if strcmp(repository,'all') || strcmp(repository,'uol')
%   qualityCheck = true;
%   globalPhaseAnalysis_unitsLaminar
% end

% qualityCheck = false;
% globalWaveformAnalysis
% if strcmp(repository,'all') || strcmp(repository,'uol')
%   qualityCheck = true;
%   globalWaveformAnalysis
% end

qualityCheck = false;
globalFRPhaseAnalysis % This is important
% if strcmp(repository,'all') || strcmp(repository,'uol')
%   qualityCheck = true;
%   globalFRPhaseAnalysis
% end

% qualityCheck = false;
% globalFRPhaseAnalysis2
% if strcmp(repository,'all') || strcmp(repository,'uol')
%   qualityCheck = true;
%   globalFRPhaseAnalysis2
% end

reverse = false;
globalPhaseAnalysis
reverse = true;
globalPhaseAnalysis

reverse = false;
globalPhaseAnalysis_halves
reverse = true;
globalPhaseAnalysis_halves

qualityCheck = false;
reverse = false;
globalPhaseAnalysis_units
reverse = true;
globalPhaseAnalysis_units

reverse = false;
globalPhaseAnalysis_unitsHalves
reverse = true;
globalPhaseAnalysis_unitsHalves

% if strcmp(repository,'all') || strcmp(repository,'uol')
%   qualityCheck = true;
%   reverse = false;
%   %globalPhaseAnalysis_units
%   reverse = true;
%   %globalPhaseAnalysis_units
%   
%   reverse = false;
%   %globalPhaseAnalysis_unitsHalves
%   reverse = true;
%   %globalPhaseAnalysis_unitsHalves
% end

if strcmpi(subpop,'all')
  qualityCheck = false;
  reverse = false;
  globalCoherenceAnalysis
  reverse = true;
  globalCoherenceAnalysis

  % if strcmp(repository,'all') || strcmp(repository,'uol')
  %   qualityCheck = true;
  %   reverse = false;
  %   globalCoherenceAnalysis
  %   reverse = true;
  %   globalCoherenceAnalysis
  % end
end



params
opt = struct();
opt.subpop = subpop;
%opt.xlim = [0.01 30];
opt.xlim = [0.01 2];
if strcmp(repository,'uol')
  if strcmp(subpop, 'all')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [outputDir filesep includeRuns filesep caDir_uol filesep unitsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalUnits_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalUnits_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
  if strcmp(subpop, 'positive')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [outputDir filesep includeRuns filesep caDir_uol_positive filesep unitsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalUnits_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalUnits_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
  if strcmp(subpop, 'negative')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [outputDir filesep includeRuns filesep caDir_uol_negative filesep unitsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalUnits_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalUnits_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
elseif strcmp(repository,'allensdk')
  if strcmp(subpop, 'all')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [outputDir filesep includeRuns filesep caDir_allensdk filesep unitsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalUnits_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalUnits_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LP','V1','V2','CA','DG'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'LP','V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','V2','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V2','CA','DG'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'VIS','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'VIS','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'VIS'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VIS',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LGN','CA','DG','V2','LP'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'LGN','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','CA','DG','V2','LP'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'V1','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
  if strcmp(subpop, 'positive')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [outputDir filesep includeRuns filesep caDir_allensdk_positive filesep unitsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalUnits_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalUnits_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LP','V1','V2','CA','DG'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'LP','V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','V2','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V2','CA','DG'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'VIS','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'VIS','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'VIS'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VIS',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LGN','CA','DG','V2','LP'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'LGN','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','CA','DG','V2','LP'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'V1','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
  if strcmp(subpop, 'negative')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [outputDir filesep includeRuns filesep caDir_allensdk_negative filesep unitsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalUnits_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalUnits_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LP','V1','V2','CA','DG'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'LP','V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','V2','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V2','CA','DG'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'VIS','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'VIS','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'VIS'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VIS',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LGN','CA','DG','V2','LP'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'LGN','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','CA','DG','V2','LP'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'V1','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
end
% close all
% 
% 
% 
% if strcmp(subpop, 'all')
%   globalEyeAnalysis
% 
%   globalEyeAnalysis_halves
% 
%   qualityCheck = false;
%   globalEyeAnalysis_units
% 
%   globalEyeAnalysis_unitsHalves
% 
%   if strcmp(repository,'all') || strcmp(repository,'uol')
% %     qualityCheck = true;
% %     globalEyeAnalysis_units
% %     
% %     globalEyeAnalysis_unitsHalves
% 
% 
% 
% %     globalMotionAnalysis
% %     
% %     globalMotionAnalysis_halves
% %     
% %     qualityCheck = false;
% %     globalMotionAnalysis_units
% %     
% %     globalMotionAnalysis_unitsHalves
% 
% %     qualityCheck = true;
% %     globalMotionAnalysis_units
% %     
% %     globalMotionAnalysis_unitsHalves
%   end
% 
% else
%   qualityCheck = false;
%   globalEyeAnalysis_units
% %   if strcmp(repository,'all') || strcmp(repository,'uol')
% %     qualityCheck = true;
% %     globalEyeAnalysis_units
% %   end
% end
% 
% 
% 
% % if strcmp(repository,'uol')
% %   if strcmp(subpop, 'all')
% %     dataRegular = load('R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol\units\globalUnits_area2pupil.mat');
% %     opt.xlim = [freqLimUOL(1) 2];
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'lS1','lRSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'VB',{'lS1','lRSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'lRSC','CA','DG'},'lS1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'lS1',{'lRSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'lRSC',{'CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'CA','DG'},'lRSC'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 2*pi];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-2*pi pi/2];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol\units\phaseDiffProfiles', opt);
% %   elseif strcmp(subpop, 'positive')
% %     opt.xlim = [freqLimUOL(1) 2];
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     dataRegular = load('R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_positive\units\globalUnits_area2pupil.mat');
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'lS1','lRSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'VB',{'lS1','lRSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'lRSC','CA','DG'},'lS1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'lS1',{'lRSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'lRSC',{'CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'CA','DG'},'lRSC'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 2*pi];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-2*pi pi/2];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_positive\units\phaseDiffProfiles', opt);
% %   elseif strcmp(subpop, 'negative')
% %     opt.xlim = [freqLimUOL(1) 2];
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     dataRegular = load('R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_negative\units\globalUnits_area2pupil.mat');
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'lS1','lRSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'VB',{'lS1','lRSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'lRSC','CA','DG'},'lS1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'lS1',{'lRSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'lRSC',{'CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi-pi/4 pi+pi/4];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'CA','DG'},'lRSC'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 2*pi];
% %     opt.legendLoc = 'SouthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-2*pi pi/2];
% %     opt.legendLoc = 'NorthEast';
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_uol_negative\units\phaseDiffProfiles', opt);
% %   end
% % elseif strcmp(repository,'allensdk')
% %   if strcmp(subpop, 'all')
% %     opt.xlim = [freqLimAllen(1) 2];
% %     opt.ylim = [-pi/2 pi];
% %     dataRegular = load('R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk\units\globalUnits_area2pupil.mat');
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'V1','CA','DG'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'LGN',{'V1','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 pi];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'CA','DG'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'V1',{'CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 pi];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 pi];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'VB',{'CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk\units\phaseDiffProfiles', opt);
% %   elseif strcmp(subpop, 'positive')
% %     opt.xlim = [freqLimAllen(1) 2];
% %     opt.ylim = [-pi/2 pi];
% %     dataRegular = load('R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_positive\units\globalUnits_area2pupil.mat');
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'V1','CA','DG'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'LGN',{'V1','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 pi];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'CA','DG'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'V1',{'CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 pi];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 pi];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_positive\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'VB',{'CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_positive\units\phaseDiffProfiles', opt);
% %   elseif strcmp(subpop, 'negative')
% %     opt.xlim = [freqLimAllen(1) 2];
% %     opt.ylim = [-pi/2 pi];
% %     dataRegular = load('R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_negative\units\globalUnits_area2pupil.mat');
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'V1','CA','DG'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'LGN',{'V1','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 pi];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'CA','DG'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'V1',{'CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 pi];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi/2 pi];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {{'CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_negative\units\phaseDiffProfiles', opt);
% %     opt.ylim = [-pi pi/2];
% %     meanPhaseProfilesSummary4({'awake'}, dataRegular.areas, {'VB',{'CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
% %       dataRegular.areaPhaseFullInterpIndividual, 'R:\CSN\Shared\Dynamics\Data\mouse_analysis_data\area2pupil_comparisons_allensdk_negative\units\phaseDiffProfiles', opt);
% %   end
% % end
% % close all