repository = 'allensdk'; % 'uol' or 'allensdk'
subpop = 'negative'; %'all', 'positive', 'negative'
fullRun = true; % Full data analyses (true) or only creating figures (false)
includeRuns = 'noRun'; % 'run', 'noRun'

params

if ~exist('allData', 'var') && fullRun
  if strcmp(repository,'uol')
    load([dataDir filesep includeRuns filesep 'allDataMUAs_uol.mat']);
  elseif strcmp(repository,'allensdk')
    load([dataDir filesep includeRuns filesep 'allDataMUAs_allensdk.mat']);
  end
end

% globalPhaseAnalysis_MUAsLaminar % run twice

globalFRPhaseAnalysis_muas

globalPhaseAnalysis_muasLocal

reverse = false; %#ok<*NASGU>
globalPhaseAnalysis_muas
reverse = true;
globalPhaseAnalysis_muas

reverse = false;
globalPhaseAnalysis_muasHalves
reverse = true;
globalPhaseAnalysis_muasHalves

params
opt = struct();
opt.subpop = subpop;
opt.xlim = [0.01 30];
if strcmp(repository,'uol')
  if strcmp(subpop, 'all')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [dataDir filesep includeRuns filesep caDir_uol filesep MUAsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalMUAs_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalMUAs_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
  if strcmp(subpop, 'positive')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [dataDir filesep includeRuns filesep caDir_uol_positive filesep MUAsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalMUAs_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalMUAs_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
  if strcmp(subpop, 'negative')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [dataDir filesep includeRuns filesep caDir_uol_negative filesep MUAsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalMUAs_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalMUAs_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Po','S1','RSC','CA','DG'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'Po','S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','RSC','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'S1','RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'RSC','CA','DG'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'RSC','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Th',{'Cx','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Po','VB'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Po','VB'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'CA','RSC','S1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','RSC','S1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Cx','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Hp',{'Cx','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'Cx'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'Cx',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'VB','CA','DG','RSC','Po'},'S1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'S1',{'VB','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {{'S1','CA','DG','RSC','Po'},'VB'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'anaesthesia'}, dataRegular.areas, dataReverse.areas, {'VB',{'S1','CA','DG','RSC','Po'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
elseif strcmp(repository,'allensdk')
  if strcmp(subpop, 'all')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [dataDir filesep includeRuns filesep caDir_allensdk filesep MUAsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalMUAs_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalMUAs_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LP','V1','V2','CA','DG'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'LP','V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','V2','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V2','CA','DG'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'VIS','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'VIS','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'VIS'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VIS',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LGN','CA','DG','V2','LP'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'LGN','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','CA','DG','V2','LP'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'V1','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
  if strcmp(subpop, 'positive')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [dataDir filesep includeRuns filesep caDir_allensdk_positive filesep MUAsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalMUAs_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalMUAs_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LP','V1','V2','CA','DG'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'LP','V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','V2','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V2','CA','DG'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'VIS','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'VIS','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'VIS'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VIS',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LGN','CA','DG','V2','LP'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'LGN','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','CA','DG','V2','LP'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'V1','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
  
  if strcmp(subpop, 'negative')
    opt.ylim = [-pi-pi/2 pi+pi/2];
    mainFolder = [dataDir filesep includeRuns filesep caDir_allensdk_negative filesep MUAsFolder];
    figFolder = [mainFolder filesep 'meanPhaseSums'];
    dataRegular = load([mainFolder filesep 'globalMUAs_ca.mat']);
    dataReverse = load([mainFolder filesep 'globalMUAs_ca_reverse.mat']);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LP','V1','V2','CA','DG'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'LP','V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','V2','CA','DG'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'V1','V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V2','CA','DG'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'V2','CA','DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Hp'},'Th'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Th',{'VIS','Hp'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','LP','LGN'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','LP','LGN'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1','Th'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'CA','V2','V1'},'DG'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA','V2','V1'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'VIS','Th'},'Hp'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'Hp',{'VIS','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi/4 pi/4];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'CA',{'DG'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'DG',{'CA'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    opt.ylim = [-pi pi];
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'Hp','Th'},'VIS'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'VIS',{'Hp','Th'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'LGN','CA','DG','V2','LP'},'V1'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'V1',{'LGN','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {{'V1','CA','DG','V2','LP'},'LGN'}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
    meanPhaseProfilesSummary3({'awake'}, dataRegular.areas, dataReverse.areas, {'LGN',{'V1','CA','DG','V2','LP'}}, dataRegular.areaFreqFullInterpIndividual, FOI,...
      dataRegular.areaPhaseFullInterpIndividual, dataReverse.areaPhaseFullInterpIndividual, figFolder, opt);
  end
end
close all

globalEyeAnalysis_muas
globalEyeAnalysis_muasHalves